# Generated by Django 3.1.7 on 2021-05-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_auto_20210520_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charities.benefactor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charities.charity'),
        ),
    ]
